#!/usr/bin/env bash
# This script will display numbers with conditions
i=1
while [ $i -le 100 ]
do
    if (($i % 3 != 0 && $i % 5 != 0))
    then
	echo $i
    elif
	(($i % 3 == 0 && $i % 5 == 0))
	then
	    echo "FizzBuzz"
    elif
	(($i % 3 == 0 && $i % 5 != 0))
	then
	    echo "Fizz"
    elif
	(($i % 5 == 0 && $i % 3 != 0))
	then
	    echo "Buzz"
	fi
	i=$((i+1))
done
