#!/usr/bin/env bash
# This script will print different phrases for different lines using the while loop with if statements
i=1
while [ $i -le 10 ]
do
    if (($i != 4 && $i != 8 ))
       then
	   echo "Best School"
    elif [ $i = 4 ]
	 then
	     echo "bad luck"
	else [ $i = 8 ]
	     echo "good luck"
	     fi
i=$((i + 1))
done
