#!/usr/bin/env bash
# This script will display numbers 1-20 and messages within the list using the while loop with case statements
i=1
while [ $i -le 20 ]
do
    echo $i
    case $i in
	4)
	    echo "bad luck from China";;
	9)
	    echo "bad luck from Japan";;
	17)
	    echo "bad luck from Italy";;
	esac
i=$((i + 1))
done
