#!/usr/bin/env bash
# This script will display the time for 12 hours and 59 minutes using the while loop
i=0
m=1
while [ $i -le 12 ]
do
    echo "Hour:" $i
    i=$((i+1))
    m=1
    while [ $m -le 59 ] 
    do
	echo $m
	m=$((m+1))	
done
done
